#Example configuration file, remember to remove "example_" from the file after adding your tokens!
#For getting a discord token: https://discord.com/developers/applications

#Bot token
token: NTg3NzYxOTE4ODY1ODM0MDIz.XP7R8Q.bT3b8AR5no-zN9cWGubXu7jAMtw
