#Example configuration file, remember to remove "example_" from the file after adding your tokens!
#For getting a discord token: https://discord.com/developers/applications

#Bot token
token: NTg3NzYxOTE4ODY1ODM0MDIz.XQGVbg.LG-nX9WuQiFKwN5M1CUQ_Uo7oG8
